### ISSUE TITLE
Wrong height and text blinks

### ISSUE THREAD

**Issue by DiabolicAngeL** [swkeep/keep-containers#2]
Hello,

I am trying to place a container, everything works perfect except that the text with instructions is blinking non-stop making it hard to read and also i think turning it around with "." and "," lags a bit while doing that.

Also, when pressing enter to place the container, the container is in the air.

I'm using it with qbcore and haven't changed anything in the script. Everything is on default.

Thanks!

**Comment by swkeep** [comment]
Hey, 
by `text with instructions` do you mean the text on `Container placer`? 
if yes then in `creator.lua` search for wait(10) and change it to wait(0) if this didn't fix it then either your PC doesn't have enough resources or something is conflicting.

and about the lag what are your PC components?

**Comment by DiabolicAngeL** [comment]
> Hey, by `text with instructions` do you mean the text on `Container placer`? if yes then in `creator.lua` search for wait(10) and change it to wait(0) if this didn't fix it then either your PC doesn't have enough resources or something is conflicting.
> 
> and about the lag what are your PC components?

Hey, the text problem is solved with wait(0)!
The lag was because of the blinking text so now it's gone. It was just lagging a bit on turning the object when the text was going like crazy.

Any idea about the container position? I'm seeing that I'm placing it fine on the ground but when i press enter this happens:
![image](https://user-images.githubusercontent.com/68332732/208915115-8ed62e17-5c6e-458a-868b-854b1a955775.png)

**Comment by swkeep** [comment]
Oh and about the `old container` it is a known issue.
Its `world offset` is totally different than other containers.
A workaround is not to align it with the surface and let it use the default position.
(in the container placer it will look underground but after placing it, it will adjust itself.)

**Comment by DiabolicAngeL** [comment]
> Oh and about the `old container` it is a known issue. Its `world offset` is totally different than other containers. A workaround is not to align it with the surface and let it use the default position. (in the container placer it will look underground but after placing it, it will adjust itself.)

Oh ok, thank you very much!
Keep up the good work!

**Comment by DiabolicAngeL** [comment]
> Oh and about the `old container` it is a known issue. Its `world offset` is totally different than other containers. A workaround is not to align it with the surface and let it use the default position. (in the container placer it will look underground but after placing it, it will adjust itself.)

Hey just a typo found.
You can close the issue, if anything else comes up I will open a new one.
Have a nice day and thank you once again! :)

![image](https://user-images.githubusercontent.com/68332732/208940317-d8d048d4-9437-475d-bf01-113269d2c0ed.png)
